---
inherit: manifest_base.yml
host: fec-prod-api
services:
  - fec-creds-prod
  - fec-ha-redis-prod
  - fec-s3-prod
env:
  PRODUCTION: True
  NEW_RELIC_ENV: production
  FEC_API_WHITELIST_IPS: true
  FEC_CACHE_AGE: 3600
